# Player Bar Interactions

|      What to Show      |     When to Show It     |
|------------------------|-------------------------|
| Play Button            | When nothing is playing |
| Pause Button           | When a song is playing  |
| Track Name             | When a song is playing  |
| Track Number           | When a song is playing  |
| Track Artist           | When a song is playing  |
| Track Current Position | When a song is playing  |
| Track Length           | When a song is playing  |
|                        |                         |